name: Verilator lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up latest Verilator
        uses: veryl-lang/setup-verilator@v1

      - name: Lint RTL
        run: ./lint.sh
